services:
  frontend:
    build: ./Frontend
    container_name: sun_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    container_name: sun_backend
    ports:
      - "9000:9000"
    env_file:
      - ./Backend/.env.docker
    volumes:
      - ./Backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    depends_on:
      - model

  model:
    image: ghcr.io/ggml-org/llama.cpp:full
    container_name: sun_model
    ports:
      - "8080:8080"
    volumes:
      - ./Model:/models
    command: >
      --server
      -m /models/qwen2-7b-instruct-q4_k_m.gguf
      --host 0.0.0.0
      --port 8080
      -c 4096